### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by ACrazyD** [Luke100000/ImmersiveAircraft#1]
Howdy, Im coming to you as a user for this mod, and wanted to know if you had a discord you hail to. Us over working on a modpack called "SkyMachina" love this mod, and would love to make sure we can do all the testing needed to help better your mod :) and give our crazy ideas as well :)

**Comment by ACrazyD** [comment]
Sorry trying to add a tag to this for ya as its just a question, not a bug report :)

**Comment by Luke100000** [comment]
Thanks for mentioning, I forgot to post that on the CurseForge page!
https://discord.gg/agxcvAdj2a
Feel free to ping me there :D
