### ISSUE TITLE
fall apart

### ISSUE THREAD

**Issue by 1936268516** [Luke100000/ImmersiveAircraft#104]
[minecraft-exported-logs-2023-12-10T14-40-48.log](https://github.com/Luke100000/ImmersiveAircraft/files/13626803/minecraft-exported-logs-2023-12-10T14-40-48.log)

**Comment by Luke100000** [comment]
Please send the full latest.log

**Comment by 1936268516** [comment]
> 请发送完整的最新.log

[crash-2023-12-10_16.42.09-client.txt](https://github.com/Luke100000/ImmersiveAircraft/files/13627059/crash-2023-12-10_16.42.09-client.txt)

**Comment by Luke100000** [comment]
While that's a good start, I really need the logs/latest.txt for as much context as possible.

**Comment by 1936268516** [comment]
> 虽然这是一个好的开始，但我真的需要日志/latest.txt 来获取尽可能多的上下文。

Sorry, I can't provide a full one either, as it crashes on startup, not sure if it's a conflict with that module.

**Comment by 1936268516** [comment]
> While that's a good start, I really need the logs/latest.txt for as much context as possible.

Ok, I found the problem, it was caused by a crash when Create started the injection flywheel, sorry thought it was that module.
