### ISSUE TITLE
The server is unable to use the module

### ISSUE THREAD

**Issue by ghost** [Luke100000/ImmersiveAircraft#107]
When I used this mod on the 1.20.1 fabric server, it seemed that it was not detected by the server, and the content of the mod could not be used within the server, even if the client did not load Immersive_ Aircraft - can also enter the server. The version used is immersive_ Aircraft-0.6.2+1.20.1 fabric

**Comment by Luke100000** [comment]
Double check you did indeed added the fabric version, and if yes please send me the server log.
