### ISSUE TITLE
Conflict between UI and Rei in Cargo Airship

### ISSUE THREAD

**Issue by ZHEAIss** [Luke100000/ImmersiveAircraft#108]
![2023-12-29_09 30 34](https://github.com/Luke100000/ImmersiveAircraft/assets/154711805/f6c3e939-dc57-4295-9b14-456563eb127b)

**Comment by Luke100000** [comment]
What version is this? I explicitly added support a while ago.

**Comment by ZHEAIss** [comment]
![11](https://github.com/Luke100000/ImmersiveAircraft/assets/154711805/4db7568c-2c57-43aa-af89-e87272502698)
Tested using Java 21 and 0.15 fabric

**Comment by Luke100000** [comment]
What you can try in the meantime is the plugin compat addon: https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items-hacks
