### ISSUE TITLE
feature request to fix common issue while playing (ocean flying)

### ISSUE THREAD

**Issue by DanielBernardy** [Luke100000/ImmersiveAircraft#109]
while playing with this i commonly fly long distances over water and as such sometimes bump the dismount button on accident adjusting my hands. so if we could either get a setting where you have to double tap the button to dismount, the plane floats so ya dont lose it underwater possibly via an upgrade item, or even some sort of beacon or xaero's minimap compatibility feature to show plane locations it would be very helpful

**Comment by Luke100000** [comment]
I can add [custom icons](https://modrinth.com/mod/xaeros-minimap) to e.g. xaeros minimap, but I don't know if it will pick it up since is not a living being.

Water aircraft is WIP.

Regarding the dismount button, a double click should be doable.
