### ISSUE TITLE
Origins Mod Compatibility Issues

### ISSUE THREAD

**Issue by ereese99** [Luke100000/ImmersiveAircraft#11]
Not sure how this is configured in the mod, but you've gotta make it so that you align the player based on eye location, because the Origin mod adjusts the player height. When using Origins mod and being a larger character, it spawns you above the aircraft, when you're a smaller character it spawns you below the aircraft / in the ground.

**Comment by Luke100000** [comment]
This is an error affecting all entities, I basically inverted the offset. It should be fixed in the upcoming update, please let me know if it also fixes origin.
