### ISSUE TITLE
Distant aircrafts?

### ISSUE THREAD

**Issue by GrandmaPork** [Luke100000/ImmersiveAircraft#111]
Love using this mod with distant horizons and I think having the aircrafts be loaded outside of render distance would be an awesome feature. Thinking specifically about servers, it would be awesome to see planes flying in the distance. I know Cracker's Wither Storm Mod is able to achieve this. Though, you would only need to load the planes in from a few thousand blocks away (or at least replace the model with like a small rectangle at extreme distances since that's all they'll be at that point. 

Would love to hear your thoughts.

**Comment by Luke100000** [comment]
I can definitely make the render distance more configurable, but entity update range is vanilla and I am not sure if I want to touch that. It may collide with optimization mods etc. I will check.

I will not use any LoDs because there wont be more than one or two aircraft anyways.

**Comment by GrandmaPork** [comment]
Awesome, I hope you can figure something out. This mod is a must-have with any large scale biome mods, like terraforged

**Comment by Luke100000** [comment]
I forgot to properly set the tracking distance. It was half the recommended value. I increase it from 5 to 12.

I wont make it configurable as this would be oddly specific, but there are mods which allows you do do that: https://www.curseforge.com/minecraft/mc-mods/entity-view-distance

The render distance (still limited by tracking distance!) can be changed in the config btw. I forgor about this already.

**Comment by GrandmaPork** [comment]
Ha, you’d think I’d actually look up a mod for something like this before bringing it up to you 🤦🏽‍♂️. I’ll try that mod out
