### ISSUE TITLE
New MC versions for 1.20.2

### ISSUE THREAD

**Issue by Hadi2007** [Luke100000/ImmersiveAircraft#120]
Could you add 1.20.2 for this mod

**Comment by Luke100000** [comment]
I have decided against porting, 1.20.1 has been established as the 1.20.x major modding version, and later versions did a lot of funky stuff I don't want to deal with. You may receive a one time port when porting to 1.21.x

**Comment by Hadi2007** [comment]
i dont know a lot about that stuff, but isnt there a way to convert it to 1.20.2  my self?

**Comment by Luke100000** [comment]
You will need Java and basic gradle knowledge

**Comment by Hadi2007** [comment]
okay, thx
