### ISSUE TITLE
Weapons Not Working (Forge 1.20.1 - Mod 0.7.1)

### ISSUE THREAD

**Issue by caseythefrog** [Luke100000/ImmersiveAircraft#129]
Weapons do not work on any of the aircraft on Forge 1.20.1 Mod Version 0.7.1. There are no other mods installed, key-binds are default, gunpowder is in the inventory, and weapon is properly mounted.

Here is a [video](https://i.imgur.com/uTYfUaY.mp4) example, and an [image](https://i.imgur.com/hJhZ24a.png) to show that the key-bind was not changed.

Non-hyper-linked Links:
• Video - https://i.imgur.com/uTYfUaY.mp4
• Screenshot - https://i.imgur.com/hJhZ24a.png

**Comment by dtangres** [comment]
@caseythefrog Sorry to interject! I have additional data to contribute to this issue.

I encountered exactly the same issue myself on a modded profile - with one additional detail: installed upgrades don't work either (at the very least, the gyroscope does not stabilize against wind effect on my machine). Have you already checked that on your machine?

**Comment by CrimsonArrow360** [comment]
This is fixed as far as I can tell just fyi.

**Comment by thefish3778** [comment]
same problem to me

**Comment by Luke100000** [comment]
Apparently there is a conflict with other gun mods, e.g. wild west guns and robs guns. Do you have those or similar mods installed?

**Comment by dtangres** [comment]
@Luke100000 At the time of my comment, I did; after removing all gun mods and testing again, this has not changed.

Additionally, caseythefrog mentioned in the original post that he had no other mods installed when the bug manifested.

**Comment by dtangres** [comment]
I have even more data. 

After creating a _new_ world in which the gun mod had never been installed, the weapons and upgrades seemed to work, but not for all ships (ex. the rotary cannon would not function at all on the biplane).

**Comment by DigitalWendigo** [comment]
#132 
Seems to be the same as my issue, so I'll just link the two together to avoid duplicates from my end. 
Haven't tested the other upgrades or weapons yet, but can confirm that the gyroscope does not do what you'd expect it to. 
I have no gun mods installed.

**Comment by Luke100000** [comment]
I found at least one issue: cannon cooldown is linked to day time, which can be paused by e.g. disabled daylight cycle. I see that at least the video this was the case.

Just respond to issue when it still fails in 0.7.2+
