### ISSUE TITLE
Cant exit aircraft after update any more

### ISSUE THREAD

**Issue by f0kx** [Luke100000/ImmersiveAircraft#13]
Like title is saying i cant rightclick to exit the aircraft any more..especally the rotorcopter i tryed

**Comment by f0kx** [comment]
ah sry its R now i have r binded to another mod so it wasnt working

**Comment by Luke100000** [comment]
if it doesn't work its a mod conflict and it would be interesting to figure out why. Does WASD and shift/space work as expected?
