### ISSUE TITLE
[Forge, 1.19.2, 0.7.3] Crash on Launch 

### ISSUE THREAD

**Issue by MadSciSlack** [Luke100000/ImmersiveAircraft#138]
The latest version [0.7.3+] crashes on startup. with a "failure to load".  There's a bunch of log about shouldDismount and throwables, but hopefully you understand this better than I do.

I'll roll this back to the previous version, but let me know if there's anything I can do to help.

Log attached below.

[latest.log](https://github.com/Luke100000/ImmersiveAircraft/files/14474263/latest.log)

**Comment by MadSciSlack** [comment]
Rolling back to 0.7.2 had the same crash.  Rolling back further.
[latest.log](https://github.com/Luke100000/ImmersiveAircraft/files/14474295/latest.log)

**Comment by MadSciSlack** [comment]
Update: Version 0.7.1 launches cleanly.

**Comment by evanbones** [comment]
Getting the same mixin crash as well

**Comment by Luke100000** [comment]
Its an issue on Architectury/Looms side, and outside my know-how. For now do not upgrade. If someone is more familiar with mixins and refmaps please help :)

**Comment by MadSciSlack** [comment]
Bummer, should we approach the Architectury team about this?  This sounds like their wheel-house.

**Comment by Luke100000** [comment]
Already done, and just got a fix from there. Tho something else broke which I will take a look at tomorrow.
