### ISSUE TITLE
Fabric 1.19.2 - 0.2.0 (Mod Incompatability with Keymap) Overriding keybind settings

### ISSUE THREAD

**Issue by EvionFox** [Luke100000/ImmersiveAircraft#14]
Hello! I appreciate all your work with this mod. Something in the latest update is messing up keybinds when used with the fabric mod Keymap https://www.curseforge.com/minecraft/mc-mods/keymap

For example, I have Iris Shaders. I un-bound "toggle shaders" from my K, but with this mod if I press K it toggles the shaders.
For Simple Voice Chat, I un-bound "Groups" from G and assigned it to another key, but pressing G brings up the group GUI.

And when I use R to dismount from an aircraft, it reloads my shaders, despite R being only set to dismount and Combat Roll.

Doing a test with only Immersive Aircraft had all the key settings working properly.
And the test with Keymap active and IA disabled had all the key settings working properly as well.
Rolling IA back to 0.1.1 fixed the issue, letting keybinds work properly again.

**Comment by Zeekicus** [comment]
Same thing is happening to my game as well on the forge version with the mod [controlling ](https://www.curseforge.com/minecraft/mc-mods/controlling) on minecraft 1.19.2 forge version 43.1.52 .

**Comment by lxsmnsyc** [comment]
Can confirm this in Fabric 1.19.2 (even w/o the Keymap mod). Tried deleting the options.txt file and also resetting the keys or giving them new keybindings, but still reverted to the default hotkey. For example, I have the "Open Chat" key set to "Enter" but I still have to press "T" to open it.

**Comment by Luke100000** [comment]
Resolved in 0.3.0, I tested it with controlling in fabric 1.19.2. Please reopen if the issue persists. 3.0.0 should be uploaded today.

**Comment by SplendidAlakey** [comment]
Just in case #23 is not the same issue, also commenting here to let you know Keymap is still not compatible with IA. Controlling works, though.
