### ISSUE TITLE
Windows Defender flags as Trojan:Script/Wacatac.B!mla

### ISSUE THREAD

**Issue by vivagabe** [Luke100000/ImmersiveAircraft#140]
Any help would be appreciated!

**Comment by Luke100000** [comment]
Most certainly a false positive, when in doubt use VirusTotal which is significantly more effective than Windows Defender
https://www.virustotal.com/gui/file/14e432a47b39f444d2bdb17663f54befc59e1004b52b6c2a7ea1ddcf25101437
