### ISSUE TITLE
1.19.4 Forge broken

### ISSUE THREAD

**Issue by Henoke-ekoneH** [Luke100000/ImmersiveAircraft#149]
In the latest version for 1.19.4, pressing the spacebar while riding a biplane causes "-1 The game crashed whilst ticking entity
 Error: java.lang.NullPointerException: Registry Object not present: immersive_aircraft:engine_start" and crashes.

**Comment by Luke100000** [comment]
I need the latest.log

**Comment by Henoke-ekoneH** [comment]
[crash-2024-04-01_17.15.19-client.txt](https://github.com/Luke100000/ImmersiveAircraft/files/14821453/crash-2024-04-01_17.15.19-client.txt)
[latest.log](https://github.com/Luke100000/ImmersiveAircraft/files/14821459/latest.log)

**Comment by Henoke-ekoneH** [comment]
Forge was not the latest version, but even the latest version did not work.

**Comment by IIIap** [comment]
same problem

[latest (81).log](https://github.com/Luke100000/ImmersiveAircraft/files/14893396/latest.81.log)

**Comment by Luke100000** [comment]
I archived/deleted affected builds
