### ISSUE TITLE
Modifying cargo sizes

### ISSUE THREAD

**Issue by VitaminJake** [Luke100000/ImmersiveAircraft#150]
Hello, 
I absolutely love your mod and have been a longtime fan of using it on my server. However, we have been trying to balance boats to be competitive with every other mode of travel, and we want to make it so they are the high cargo option. Is it possible to configure how much inventory the planes have? Or would such functionality be easy to add? Thanks so much again for your mod.

**Comment by Luke100000** [comment]
Yes you can overwrite aircraft definitions using datapacks: https://github.com/Luke100000/ImmersiveAircraft/tree/1.19.2/common/src/main/resources/data/immersive_aircraft/aircraft
