### ISSUE TITLE
Fabric 1.20.1 Banners only showing base color

### ISSUE THREAD

**Issue by UnsaidRaine** [Luke100000/ImmersiveAircraft#160]
![2024-05-10_19 01 40](https://github.com/Luke100000/ImmersiveAircraft/assets/97511824/439298d9-4474-4e25-bc8e-1824d1a7abb3)
![2024-05-10_19 01 29](https://github.com/Luke100000/ImmersiveAircraft/assets/97511824/7955b5d8-6515-4c78-9ea4-69a3c119176a)

It used to show a zoomed in glitch banner, before it was not visible.

**Comment by Luke100000** [comment]
Hi! Can you test without any other mod as well as with this specific banner please:

```
/give @p minecraft:yellow_banner{BlockEntityTag:{Patterns:[{Color:13,Pattern:"mr"},{Color:3,Pattern:"moj"},{Color:15,Pattern:"bo"},{Color:15,Pattern:"bs"},{Color:15,Pattern:"ts"},{Color:15,Pattern:"gru"}]}}
```

Let's also merge with #125

Based on how many people find this issue its probably something fundamental, yet I can not reproduce this myself.

**Comment by kj4lxc** [comment]
![image](https://github.com/Luke100000/ImmersiveAircraft/assets/1366040/6a88e223-de22-418f-a824-a9f7833aa696)

Using this mod pack https://www.curseforge.com/minecraft/modpacks/cstmgames-creative-tendencies
