### ISSUE TITLE
[Suggestion] Option to use vanilla dismount button setting

### ISSUE THREAD

**Issue by obszczany** [Luke100000/ImmersiveAircraft#161]
Im playing on a controller using controlify mod, and got it to work just great. the only reason is that i cant dismount the vehicle even if i binded it correctly. when entering plane it even shows the default dismount button (probably because it is a mount). This as an option would fix lots of issues with key mods and its really a simple solution.

EDIT: also i dont know if this will help to do anything but i play on 1.20.1 version

**Comment by Luke100000** [comment]
Let's merge with #90 :)
