### ISSUE TITLE
 it  consume 0 in multiplayer

### ISSUE THREAD

**Issue by g-mero** [Luke100000/ImmersiveAircraft#162]
I love your mod, but it really consume nothing in multipaly game on Lan.
Fabric 1.20.1, Immersive Aircraft - 1.0.0

**Comment by g-mero** [comment]
Actually, same isuue in sigleplayer

**Comment by g-mero** [comment]
I fork your project and rebuild it, now it works fine, I really dont konw what happed xD

**Comment by Luke100000** [comment]
I fixed it in the last commit, its not published yet tho ^^
https://github.com/Luke100000/ImmersiveAircraft/commit/60ba17b9211faf560578a370b1e3897708233e04

**Comment by g-mero** [comment]
Thanks. By the way, I notice the Airship is slower than the Gyrodyne, which makes the Airship a less cost-effective option (really need a faster two-man aircraft that has an engine). And is there any plan to make  the aircraft drop its crafting materials upon crashing or sustaining damage. Currently, neither my friend nor I are concerned about crashes as they don't result in any losses. Additionally, it would be more reasonable if repairs required materials like iron. Thanks for your work again.

**Comment by Luke100000** [comment]
You can turn on explosions in the config if you don't want your friends to crash :)
