### ISSUE TITLE
request to have version 1.0.1 in 1.18.2

### ISSUE THREAD

**Issue by r632** [Luke100000/ImmersiveAircraft#164]
my friends and I have a server with more than 160 mods in 1.18.2, it is absolutely impossible for us to upgrade to 1.20, please could you make the mod compatible with 1.18?

**Comment by Luke100000** [comment]
Looking at the difference https://github.com/Luke100000/ImmersiveAircraft/compare/EOL/1.18.2...1.20.1
I don't think its worth the work.
