### ISSUE TITLE
[Suggestion] Switch aircraft assembly to a multiblock summoning (like the Wither)

### ISSUE THREAD

**Issue by Truemudkip** [Luke100000/ImmersiveAircraft#167]
Could be the only way to make an aircraft in survival, could be a configurable alternative, either way, actually placing out blocks to make the aircraft would be really cool. One issue would be the inability to edit aircraft recipes for modpacks (or making it a giant hassle), but I think it'd be a great addition.

**Comment by Luke100000** [comment]
This feels out of scope and could be implemented as a separate mod with more mod coverage and proper data driven interface
