### ISSUE TITLE
[Bug] Gyrodyne takes off instantly when animals on board

### ISSUE THREAD

**Issue by Fros1er** [Luke100000/ImmersiveAircraft#168]
Version: minecraft 1.20.1 with ImmersiveAircraft 0.7.5

How to reproduce:
1. Put a gyrodyne on the ground, lead an animal(chicken and cow tested) to it and let it board
2. Take off and land once.
3. The gyrodyne can take off instantly now.

**Comment by Luke100000** [comment]
Technically thats lore accurate, the entity keeps pedalling :)

**Comment by Fros1er** [comment]
So it's actually a feature, not a bug....?

To be honest, I like it. It looks like an easter egg and it was quite fun when my friend found it in our server :) 
Maybe we should close the issue?
