### ISSUE TITLE
Error log no data fixer

### ISSUE THREAD

**Issue by psoizzac** [Luke100000/ImmersiveAircraft#169]
Fabric 0.15.11
1.20.1 MC version

unsure if conflicts:

[10:27:01] [Render thread/ERROR]:
 No data fixer registered for immersive_aircraft:gyrodyne
[10:27:01] [Render thread/ERROR]:
 No data fixer registered for immersive_aircraft:biplane
[10:27:01] [Render thread/ERROR]:
 No data fixer registered for immersive_aircraft:airship
[10:27:01] [Render thread/ERROR]:
 No data fixer registered for immersive_aircraft:cargo_airship
[10:27:01] [Render thread/ERROR]:
 No data fixer registered for immersive_aircraft:warship
[10:27:01] [Render thread/ERROR]:
 No data fixer registered for immersive_aircraft:quadrocopter
[10:27:01] [Render thread/ERROR]:
 No data fixer registered for immersive_aircraft:bullet
[10:27:01] [Render thread/ERROR]:
 No data fixer registered for immersive_aircraft:tiny_tnt

**Comment by Luke100000** [comment]
No thats fine, just Minecraft having a stroke :)

Starting with 1.21 I need to deal with this in more detail, then it will be gone as well.
