### ISSUE TITLE
Cannot find Warship recipe

### ISSUE THREAD

**Issue by Synkronized1999** [Luke100000/ImmersiveAircraft#172]
HELP ME PLEASE I CANNOT FIND IT AND IVE BEEN SEARCHING FOR SO LONGGGG

**Comment by Luke100000** [comment]
For modding in general I highly recommend JEI/REI or similar.
https://github.com/Luke100000/ImmersiveAircraft/blob/dbc036b65e26795e167443ca8c224134818e84c7/common/src/main/resources/data/immersive_aircraft/recipes/warship.json
