### ISSUE TITLE
Forge 1.19.4 crashes

### ISSUE THREAD

**Issue by Flershnork** [Luke100000/ImmersiveAircraft#175]
All versions of the mod for Forge 1.19.4 post 0.7.1 crashes, either on loadup or attempting to play a sound. 
To me, it looks like it is an issue with the entities trying to point to the sound as they play perfectly fine when using the /playsound command.
Forge also detects the sounds as missing when playing a world made with the 0.7.1 version of the mod to the 0.7.9 version.

Latest Log (moving version) - https://mclo.gs/uZ5hTK0

Latest Log (crashing) - https://mclo.gs/ndHqwvE

Crash Report - [crash-2024-06-23_20.47.00-client.txt](https://github.com/user-attachments/files/15948582/crash-2024-06-23_20.47.00-client.txt)

**Comment by Luke100000** [comment]
Yes, Forge 1.19.4 is confirmed to be broken but I can't get it to run locally and lost interest in fixing Forge.

**Comment by Luke100000** [comment]
Merged with #149
