### ISSUE TITLE
Incopat with Supplementaries mod

### ISSUE THREAD

**Issue by GamerTable** [Luke100000/ImmersiveAircraft#178]
On minecraft 1.20.1 Fabric with Immersive Aircraft 1.0.1 and Supplementaries 2.8.17 banners do not display properly on planes
![image](https://github.com/Luke100000/ImmersiveAircraft/assets/114619268/e80d6cbc-9e9e-48e8-b6f0-51777e0522dc)

**Comment by Luke100000** [comment]
Merged with #125

**Comment by GamerTable** [comment]
Cool, btw I was using the banner that you mentioned on the other issue, forgot to mention that earlier lol
