### ISSUE TITLE
Unable to place warship

### ISSUE THREAD

**Issue by Aero-Seira** [Luke100000/ImmersiveAircraft#180]
unable to place warship after adding mods but i did not find which one caused that , maybe there were some conflicts and im still testing it

**Comment by Aero-Seira** [comment]
using /summon  we got the warship with no errors, only the warship item not works ,

**Comment by Luke100000** [comment]
the ship is big, make sure it has space and you are far enough away. I will add a proximity warning next update

**Comment by Aero-Seira** [comment]
> the ship is big, make sure it has space and you are far enough away. I will add a proximity warning next update

Thanks for replying 
I've been trying that in enough space and it didn't work
There was someone else encountering the same problem,so im still considering it a conflict ,later I'll try finding out the mod causing that
Loving you and your works :)

**Comment by Luke100000** [comment]
0ad497d
