### ISSUE TITLE
Support for controllable mod 1.20.1

### ISSUE THREAD

**Issue by Buttersxx** [Luke100000/ImmersiveAircraft#184]
I see 2 issues are open with controller support. But I don’t see any recommendations or updates regarding controller support. 
Is controller support in the works? Or is there a work around to get it to work?

**Comment by Luke100000** [comment]
merged with #90, if you see two open issues, why would you open another one?

**Comment by Buttersxx** [comment]
Well are you going to add support for controllable mod?

**Comment by Luke100000** [comment]
I would have closed the issue otherwise ^^
