### ISSUE TITLE
Suggestion:Mutually exclusive engines

### ISSUE THREAD

**Issue by DaPuffer** [Luke100000/ImmersiveAircraft#186]
Perhaps,a config option to make the nether engine,eco engine and boiler mutually exclusive,to prevent getting less fuel requirement and more engine power for free by using eco and nether engines together. Same with industrial gears and sturdy pipes.

**Comment by Luke100000** [comment]
You are not getting it for free, you pay with relatively expensive items. Especially the later example is a perfect example of how the upgrades are intended. I would go for simplicity here :)
