### ISSUE TITLE
Mod compatibility

### ISSUE THREAD

**Issue by wsxiya** [Luke100000/ImmersiveAircraft#189]
When on a plane, the two status bars overlap
![1`)82%K2JUX3(8@)2(A(BY1](https://github.com/user-attachments/assets/f6022d9c-181b-4bac-87bf-589a44ed304b)

**Comment by wsxiya** [comment]
mod homepage:https://www.curseforge.com/minecraft/mc-mods/legendary-survival-overhaul
“Tough As Nails”is also like this

**Comment by Luke100000** [comment]
You can offset the bar in the config

**Comment by wsxiya** [comment]
> 您可以在配置中偏移柱线

thank you for your reply
