### ISSUE TITLE
Immesive Aircrafts and Immersive Instruments together! (Suggestion)

### ISSUE THREAD

**Issue by AviatorFrog** [Luke100000/ImmersiveAircraft#192]
Be able to play the instruments from Immersive Instruments when piloting an aircraft from Immersive aircrafts. 
I would be so cool to play a song while traveling long distances!

**Comment by willis1030** [comment]
I would like to keep seperate of these two mods. I think simple function is better then force players to accept all they don't want. Keep rights of selection for us please!

**Comment by Luke100000** [comment]
Nobody was talking about merging the mods. OP is experiencing this bug here: https://github.com/Luke100000/ImmersiveMelodies/issues/70
