### ISSUE TITLE
lose ship guests when going through an immersive portals dimension stack portal.

### ISSUE THREAD

**Issue by therealKoolant** [Luke100000/ImmersiveAircraft#195]
Very specific issue, but I'm using immersive portals 1.20.1 fabric on forge via sinytra connector. (yes i know it's not supported) I have a dimension stack world, and once you cross a portal, the plane (I tested the battleship) goes through and keeps you, but all mobs onboard fall out. (and probably die due to fall damage).
Don't know if this issue persists on native forge iportals.

**Comment by Luke100000** [comment]
And would a boat work?

**Comment by therealKoolant** [comment]
ah, yes they still fall out in boats. seems to be an Iportals issue. mb

**Comment by Luke100000** [comment]
Maybe they were lazy and only consider the primary passenger :)
