### ISSUE TITLE
Request for update to 1.21.1

### ISSUE THREAD

**Issue by mkaisercross** [Luke100000/ImmersiveAircraft#198]
Would love to include this mod in a 1.21.1 modpack I am working on

**Comment by Luke100000** [comment]
#193

**Comment by mkaisercross** [comment]
Curseforge and Modrinth are saying the latest version available is 1.20.1. Am I missing something?

**Comment by Luke100000** [comment]
You missed the linked issue #177 :) I don't like version requests to clutter the tracker, it's not an issue, its a general development direction.
