### ISSUE TITLE
(BUG) You can carry infinite villagers in the vehicles

### ISSUE THREAD

**Issue by ghost** [Luke100000/ImmersiveAircraft#202]
As the title says, this is a broken mechanic cuz you can go a villager town and put all the villagers into one vehicle of this mod. I am using another mod called "Carry On" so i can carry them until the vehicle and i can stack them in the same vehicle. I want to fix this cuz we are playing on a server and people are starting to abuse of this.

Thanks bro, i really love this mod, one of the bests in my server :)

**Comment by Luke100000** [comment]
Stacking entities is a carry on feature, and works on every vehicle. It's not Aircraft related :)

**Comment by ghost** [comment]
Thank you for your fast answer, keep the good job <3
