### ISSUE TITLE
Ad Astra 1.16.6?

### ISSUE THREAD

**Issue by Greg727** [Luke100000/ImmersiveAircraft#204]
I updated the mod for 1.20.1, the file number being 1.1.1

I loaded the game and it told me that Immersive Aircrafts only supports ad astra 1.16.6

The latest mod version of Ad Astra for 1.20.1 is 1.15.8, while the latest mod version of Ad Astra period is 1.16.5, which is only available for 1.20.4, so Ad Astra 1.16.6 doesn't exist yet

**Comment by Luke100000** [comment]
You need to allow beta versions.

**Comment by Greg727** [comment]
I did do that, and still nothing

**Comment by Luke100000** [comment]
Ahhh typo, should be 1.15.6. Try IA 1.1.2 please.
