### ISSUE TITLE
[Suggestion] Shift-Clicking banners

### ISSUE THREAD

**Issue by Mirka1405** [Luke100000/ImmersiveAircraft#205]
Hi!
Right now, when you shift-click a banner, it goes into the fuel slot, which is quite frustrating. It would be nice if banner items automatically went into the banner slot.

**Comment by Luke100000** [comment]
Hmm should not happen in recent versions, what version and aircraft did you try?

**Comment by Mirka1405** [comment]
v0.5.2 on 1.18.2 fabric, on a biplane. I checked updates using prism launcher a few days ago, so I'm unsure whether this is the newest version.

**Comment by Luke100000** [comment]
Ah yes, 1.18.2 has not been supported for a long time
