### ISSUE TITLE
Can't fly plane

### ISSUE THREAD

**Issue by Hammer512** [Luke100000/ImmersiveAircraft#206]
i hit space and nothing happens, i rebind every control to space, nothing happens, i have tried everything and i still cant fly a biplane or quadcopter, yet i can fly a gyrodyne completely fine

**Comment by Luke100000** [comment]
I need more information, version, modloader, does it work on singleplayer, does it work without any other mods, and if yes, track down the conflicting mod

**Comment by zajarka** [comment]
> I need more information, version, modloader, does it work on singleplayer, does it work without any other mods, and if yes, track down the conflicting mod

Version - 1.20.1, ModLoader - Fabric, Its work on singleplayer, dont working only on server only on my assembly

**Comment by Luke100000** [comment]
Merged with #208
