### ISSUE TITLE
Question about modifications for aircrafts

### ISSUE THREAD

**Issue by oleksandrshtonda** [Luke100000/ImmersiveAircraft#209]
Hello, Luke100000!

I really like this mod and I have some questions:
1) Could you describe effercts of each modification or send an article when they described? I have tryed to find it myself but I didn't...
2) If we take the power of regular airplane as 1 and we put Nether Engine, the power is 1.4 now. But if I want to put also strong pipes (it increases power 10%) so what is power of the airplane? power = 1.4? power = 1.1? power = 1 + (1*0.40) + (1*0.10) or power = 1 * 1.4 * 1.1?
3) Do you need help to translate the mod to Ukrainian language? If you do, I can help your for free :)

Have a nice day

**Comment by Luke100000** [comment]
Hi!

Upgrades are calculated here: https://github.com/Luke100000/ImmersiveAircraft/blob/1.20.1/common/src/main/java/immersive_aircraft/entity/InventoryVehicleEntity.java#L84
and are additive, so in your case its 1 + 0.5.
except for negative values (e.g. -10%), it's multiplicative, so 1 * 0.9.

To make math consistent, negative effects are applied first, then positive ones.

So a -10%, +30%, -20%, +40% will be 1 * 0.9 * 0.8 + 0.3 + 0.4 = 1.42 = 42% total improvement

Translations are always welcome, usually via Crowdin :) https://crowdin.com/project/immersive-collection

**Comment by oleksandrshtonda** [comment]
Thanks for answers for 2nd and 3rd question. Could you describe the "Enhanced Propeller", "Gyroscope" and "Improved Landing Gear"? How they influence on the biplane? Could you describe, please?

**Comment by Luke100000** [comment]
Propeller increases max speed, gyroscope disables wind wobbling, and the landing gear increases acceleration on the ground.
