### ISSUE TITLE
Sword attacks in an airship accelerates it

### ISSUE THREAD

**Issue by Howardohyea** [Luke100000/ImmersiveAircraft#21]
Attacking with a sword while in the airship accelerates it, and when spammed the ship can reach 100+ blocks per second. This doesn't seem to work with items or other tools (like axes) and the attack doesn't need to be knockback attacks to accelerate the ship.

From what I can observe each sword attack accelerates the airship by about 10m/s and spamming left click can stack the acceleration up. 

I'm on Version 0.2.1 and I haven't tried replicating it in 0.3.0 or with other vehicles, like biplanes. I will update this when I find anything else worth noting.

**Comment by Luke100000** [comment]
Thanks for the report. This issue should be fixed in 0.3.0, it was indeed knockback being applied.

**Comment by Howardohyea** [comment]
> Thanks for the report. This issue should be fixed in 0.3.0, it was indeed knockback being applied.

Ah yeah I didn't read the 0.3.0 changelog, and I just found out an unenchanted sword doesn't speed the ship up. 

I also tried replicating this in 0.3.0 and yeah, it's fixed. Thanks!
