### ISSUE TITLE
Gyrodane

### ISSUE THREAD

**Issue by b0nkers96** [Luke100000/ImmersiveAircraft#213]
Is there a way to change the hunger values of how much it depletes? As i am using it on a very difficult modpack that makes getting vanila mob animals hard to find.

**Comment by Luke100000** [comment]
With datapacks you can control the `fuel` field, or in the config is a global fuel modifier.

https://github.com/Luke100000/ImmersiveAircraft/tree/1.20.1/common/src/main/resources/data/immersive_aircraft/aircraft
