### ISSUE TITLE
Add support to EMI's UI so they don't clash with some Immersive Aircraft's UI

### ISSUE THREAD

**Issue by Aruman-Zen** [Luke100000/ImmersiveAircraft#223]
Some UI from the ships, are too big and clash with the UI from EMI, i heard that you can add some exclusions to tell EMI to not put itself over the inventory UI
![image](https://github.com/user-attachments/assets/b03ebbc9-e7ef-4663-a79f-09bf70b97c32)

**Comment by Luke100000** [comment]
~~NEI support broke with 1.21~~ unrelated

**Comment by Luke100000** [comment]
It seems the intended way is to just install JEI alongside it, and JEI then loads the plugin addings said compat
