### ISSUE TITLE
Downgrade newest version by one [1.21]

### ISSUE THREAD

**Issue by BeagleNF404** [Luke100000/ImmersiveAircraft#226]
Since 1.21 and 1.21.1 are basically the same, could it be possible to make 1.21 available too? I'd love to use it on my server, but the server is 1.21

**Comment by Luke100000** [comment]
I will not support two versions of the same major. If it is basically the same, it should work anyway, what is the error?

**Comment by BeagleNF404** [comment]
Aternos is picky with versions. Thats why, yes they're basically the same but aternos doesent think so.

**Comment by BeagleNF404** [comment]
So I would be very grateful if you could port it to 1.21 :)

**Comment by BeagleNF404** [comment]
So is it possible for you to do it?

**Comment by Luke100000** [comment]
possible yes, but I'm still very against supporting a second version. I will consider marking it as compatible in the next version

**Comment by BeagleNF404** [comment]
tysm! :D
