### ISSUE TITLE
Cant craft on servers

### ISSUE THREAD

**Issue by itztonii** [Luke100000/ImmersiveAircraft#227]
as the title says, im not able to craft anything from the mod in a server that has the mod installed. the planes work and everything and we know because we had to use creative mode to cheat it in but they work fine, its just that stuff from the mod isnt craftable for some reason and we dont want to cheat stuff in.
The mod works fine in survival mode i can craft and stuff. Also, JEI doesnt even show the crafting recipe IN the server specifically but it does in solo worlds

![image](https://github.com/user-attachments/assets/5199c876-a192-4b2f-b4e4-6f6ed878d4b4)

**Comment by Luke100000** [comment]
server log please

**Comment by itztonii** [comment]
im not the owner of the server but i can ask for it when they wake up, sorry

edit, i also found another issue where banners glitch out 

![2024-11-27_05 25 34](https://github.com/user-attachments/assets/470b0ae4-a98c-4dd6-8be6-b88b460b24bd)

**Comment by Luke100000** [comment]
Double-check that both client and server are up to date

**Comment by itztonii** [comment]
i tried all the versions available on modrinth for 1.21.1 and its still the same thing

**Comment by itztonii** [comment]
heres the server log 
[latest.log](https://github.com/user-attachments/files/17954815/latest.log)

**Comment by Luke100000** [comment]
Thanks! This is not the newest version, and is missing the fixes for both recipe and banner rendering.

**Comment by itztonii** [comment]
about that, we had to use an older version because it keeps crashing the server

**Comment by Luke100000** [comment]
Well, thats a separate problem ^^ Send the crashlog
