### ISSUE TITLE
[Feature Request] Roll direction for biplanes 

### ISSUE THREAD

**Issue by MahnoKropotkinvich** [Luke100000/ImmersiveAircraft#228]
As an Ace Combat player, I've found that incorporating roll direction allows for a wider range of maneuvers beyond simply turning left or right, much like driving a car. While adding roll direction requires significant effort, it enhances gameplay by making biplanes distinct vehicles and offering a more diverse gaming experience.

**Comment by MahnoKropotkinvich** [comment]
And, providing an option to switch between the traditional mode and the roll direction enabled pro mode.

**Comment by Luke100000** [comment]
I understand you, but I decided on a 2-axis movement in favor of easier vehicle movements; after all, it's Minecraft and not a simulator :)
There was a pull request going on somewhere, but I lost track of it.

**Comment by Luke100000** [comment]
Ah here it is: #196
