### ISSUE TITLE
[Request] 1.19.2 Backport Controller Support/Model Fixes

### ISSUE THREAD

**Issue by 123ghaksd** [Luke100000/ImmersiveAircraft#229]
I noticed controller support for "Controllable" is added to more recent MC versions as well as the model offset fixes for the Gyrodyne. Would be great to just get a backport of these features so that the final 1.19.2 version is polished. A backport would be much appreciated.

**Comment by Luke100000** [comment]
Can do, but controller support is still on the todo, if it works then by accident ^^

**Comment by 123ghaksd** [comment]
Oh may have misread about the controller support, but yeah that'd be great to at least get the model fix. Appreciate you.
