### ISSUE TITLE
Camera and keybind reset

### ISSUE THREAD

**Issue by ClowreedII** [Luke100000/ImmersiveAircraft#23]
I'm using this mod version 0.3.0 in a server and everytime I log in after closing + opening the game, the keybind for going down resets (I use Left Control and it resets back to Left Shift which is the default I believe)
Also the camera resets to 3rd person view, I use 1st person view

This wasn't happening on previous versions

**Comment by zaeonNineZero** [comment]
I've also had this issue on the Forge version for 1.19.2. It seems to be the same problem as in https://github.com/Luke100000/ImmersiveAircraft/issues/14 although it occurs even when Controlling is removed.

**Comment by SplendidAlakey** [comment]
Also having this issue on Quilt and Fabric. With Keymap it resets. With Controlling it works, but I'm getting errors in logs:
```
[20:35:03] [Render thread/ERROR]: ########## GL ERROR ##########
[20:35:03] [Render thread/ERROR]: @ Render
[20:35:03] [Render thread/ERROR]: 65540: Invalid scancode -1
```
