### ISSUE TITLE
Failed to create player model

### ISSUE THREAD

**Issue by WhatIsGetHub** [Luke100000/ImmersiveAircraft#25]
Hello there,

I get a crash everytime I install your mod & here's the log:

[crash-2023-02-06_13.20.58-client.txt](https://github.com/Luke100000/ImmersiveAircraft/files/10662003/crash-2023-02-06_13.20.58-client.txt)

**Comment by Luke100000** [comment]
```
Caused by: java.lang.NullPointerException: Cannot invoke "com.google.common.collect.ImmutableMap.entrySet()" because "ladysnake.illuminations.client.Illuminations.OVERHEADS_DATA" is null
```
Looks like a mod conflict with illuminations. It looks more like an issue on their side and I wasn't able to find a quick fix. Maybe report it to their issues tracker as they may recognize this issue.

**Comment by WhatIsGetHub** [comment]
It appeared to be just updating a certain required library for your mod.

Thanks anyways for your precious time.
