### ISSUE TITLE
Using bucket-based fuels deletes bucket

### ISSUE THREAD

**Issue by petthepetra** [Luke100000/ImmersiveAircraft#36]
Putting fuels contained within a bucket into an aircraft will consume the entire item, rather than leaving behind an empty bucket in the fuel slot. Currently only applies to the Lava Bucket as only vanilla fuel sources seem to be usable right now, but if that changes in the future I imagine the issue will also carry over to modded fluids.

**Comment by Luke100000** [comment]
Quite hungry that engine ^^
