### ISSUE TITLE
[Feature Request] Configurable aircraft fuel source list

### ISSUE THREAD

**Issue by petthepetra** [Luke100000/ImmersiveAircraft#37]
The newly added fuel features are a great improvement, but right now it seems to only accept vanilla fuels. Changing this to accept all furnace fuels (like modded furnaces and generators do) would be a simple and good solution, but it would be fantastic for modpack balancing if you could (perhaps optionally?) set a custom list of fuels for the vehicles to accept.

**Comment by Luke100000** [comment]
Vanillas fuel list is a mess. I can feel that this might change in the future but for now I agree, a config id map sounds like an good solution.
