### ISSUE TITLE
[1.16.5] Fuel Mechanic?

### ISSUE THREAD

**Issue by Exokyhh** [Luke100000/ImmersiveAircraft#38]
Using: [[Forge 1.16.5] Immersive Aircraft - **0.3.2**]

Hi! You might remember me from the immersive-armor mod, where we helped each-other fixing the bugs the mod had xD. 
Anyway, I was wondering if you could add a fuel mechanic (I'm not sure since I've tested only 1.16.5, but I think the feature is already implemented in the newer versions of minecraft) in order to help balancing this vehicles. Without fuel, they seems a bit broken/abusable, since they easily overcome every other way of transportation. I love them, and atm im working on a new modpack around RPG, so this mod would fit perfectly into it! 

Hope you answer soon, 
_your Dear Tester_

**Comment by Luke100000** [comment]
I'm waiting for a bit more feedback and then backport those changes :)

**Comment by Exokyhh** [comment]
Wonderful! I'll patiently wait for the new version

**Comment by Luke100000** [comment]
Added btw
