### ISSUE TITLE
Can't fly on latest version

### ISSUE THREAD

**Issue by skunkmommy** [Luke100000/ImmersiveAircraft#39]
This is not just a repeat of #30 although I suspect there's a binding issue.
I can turn but I can't start flying.
I'm on 1.19.3 using version 0.4.1 of the mod.

**Comment by Luke100000** [comment]
Did you fuel the engine? If yes, try to use another key, someone found a mod incompatibility which blocks the jump key (space by default).

**Comment by skunkmommy** [comment]
> Did you fuel the engine? If yes, try to use another key, someone found a mod incompatibility which blocks the jump key (space by default).

I'm in creative. Do you need fuel in creative now? Please add an infinite fuel option for people who want

**Comment by skunkmommy** [comment]
How do you fuel engines? There's no 'fuel' item so how do I do it?

**Comment by Luke100000** [comment]
Anything that burns

**Comment by skunkmommy** [comment]
> Anything that burns

Where do i put it? just use on the aircraft?
EDIT: oh you shift click
Still think there should be an infinite fuel option and also think there should be some documentation

**Comment by Luke100000** [comment]
It says "no fuel" over your hotbar, and there is a fuel slot, with a tooltip, using the same concept as a furnace thus being the most vanilla thing possible. I disagree on the documentation here.
Inventory can also be access like a horse using E.
Yes to the creative one. You can set fuel consumption in the config.

**Comment by skunkmommy** [comment]
EDIT: Fuel consumption 0 does work, but I still need to put an item in the fuel slot. Please disable this behaviour when fuel consumption is set to 0. For now I'm gonna use 1.3.1
