### ISSUE TITLE
Unable to move because of update

### ISSUE THREAD

**Issue by FEBtheKB** [Luke100000/ImmersiveAircraft#40]
Hi,
Because of the new 0.4.1 update for Fabric, now keybinds need to be reset because otherwise they override the vanilla movement keys, making you unable to move. The only way to "fix" this is to use other keys, which is really uncomfortable considering that a heavily modded modpack has its limits. Why were they not overriding before, but now all of a sudden they are? I would like to be able to use, once again, the vanilla keys for movement and ease of use. Please, let me know if there's a config I can use.

**Comment by Luke100000** [comment]
If you do not overwrite the keys, the use the vanilla keys. What have you modified?

**Comment by FEBtheKB** [comment]
Basically what I mean is that with this new update, if I try to put the controls as WASD, they override the vanilla controls and as such you can't move. This didn't happen in previous updates.

**Comment by Luke100000** [comment]
This is vanilla behavior, thats why you should NOT overwrite it if you use the default movement anyways. Earlier version used a custom keybind system, breaking compatibility with a lot of mods.

**Comment by Luke100000** [comment]
At some time today I will push a version which offer both systems. By default I use the old one, where you can bind multiple keys. If that fails for whatever reason, the config allows for plan B.
