### ISSUE TITLE
cant craft

### ISSUE THREAD

**Issue by jjcolsg** [Luke100000/ImmersiveAircraft#41]
Hi, probably easy question here. Just started playing my server with a friend, its also my first modded server. I try to craft any of the items and nothing happens. Am I missing something? perhaps a setting per player or the server? Yes the mods and us are running the same version as t he server i.e. 1.19.2. we also have simple planes,  citadel, and journey map installed

**Comment by Luke100000** [comment]
Some modpacks overwrite the recipes, e.g. to work better with Create. Use JEI or similar instead.

**Comment by jjcolsg** [comment]
so, should I start by removing simple planes to try? sorry, whats JEI?

**Comment by Luke100000** [comment]
Simple planes is definitely not the culprit.
JEI https://www.curseforge.com/minecraft/mc-mods/jei is a nice tool to query recipes, especially in modded environments a live safer.

**Comment by jjcolsg** [comment]
omg thanks for it, in part, managed to installed it, its working because I tested the show recipe feature and works, still not showing me recipes for propellers, thats be cause probably both plane mods are conflicting between them?

**Comment by Luke100000** [comment]
Ohh yea that might be an issue. There is a mod fixing conflict but I cant remember the name

**Comment by jjcolsg** [comment]
I will see if I can find that mod, but still getting issue, I removed one of the mods, and still no recipe found for it

**Comment by jjcolsg** [comment]
A side note, my friend told me he created a single player world with the launcher. And he could use all the mods, so must be something via the server console

**Comment by jjcolsg** [comment]
luke, managed to fix it. was running it on monecraft 1.19.2 and not on forge 1.19.2. Thanks for the help!
