### ISSUE TITLE
Strange Server Issue [1.18.2]

### ISSUE THREAD

**Issue by GrandmaPork** [Luke100000/ImmersiveAircraft#42]
When I attempt to join a server with this mod installed, I get this error
Optifine is installed on client but this might be a mod incompatibility since this didn't happen until recently, I just cannot find the mod that's causing this
![2023-03-25_15 56 28](https://user-images.githubusercontent.com/109642282/228690846-51de8166-4cdf-4f54-b2c8-304356981ba1.png)

**Comment by Luke100000** [comment]
Double check server and client have the same version

**Comment by GrandmaPork** [comment]
They had the same version

**Comment by Luke100000** [comment]
Is this fabric or forge?

**Comment by GrandmaPork** [comment]
forge 40.2.1

**Comment by Luke100000** [comment]
And when you remove aircraft from the client, can you join? Also please send me the exact file name of the jar on server and client.

**Comment by GrandmaPork** [comment]
nevermind, somehow the server ended up with 3.2.1 and the client had 4.2.1. Not sure how this happened since im using the curseforge launcher and they had the same versions at some point
