### ISSUE TITLE
Attempting to enter gyrocopter on 0.4.2 crashes game (1.16.5)

### ISSUE THREAD

**Issue by BrawleyGithub** [Luke100000/ImmersiveAircraft#46]
Right clicking a gyrocopter in survival (and maybe creative) to enter it crashes my game with this crash log:

[crash-2023-04-05_17.00.13-client.txt](https://github.com/Luke100000/ImmersiveAircraft/files/11163498/crash-2023-04-05_17.00.13-client.txt)

Thanks for the mod though! So far it's everything I wanted for aircraft.

**Comment by Exokyhh** [comment]
Same here

[crash-2023-04-06_15.28.00-client.txt](https://github.com/Luke100000/ImmersiveAircraft/files/11171074/crash-2023-04-06_15.28.00-client.txt)
