### ISSUE TITLE
Engine dont start

### ISSUE THREAD

**Issue by GhepardoDelWeb** [Luke100000/ImmersiveAircraft#47]
engine dont start anymore and i cant dismount from the airship, (the keybindings are all set good) the engine is just off

**Comment by Luke100000** [comment]
which version, which modloader, did you fuel the engine?

**Comment by GhepardoDelWeb** [comment]
version 1.19.3 on fabric version o.14.17 and i dont know how to fuel it

**Comment by Luke100000** [comment]
Open inventory, add furnace fuel

**Comment by GhepardoDelWeb** [comment]
there is a specific way to open the inventory of the airship? i am clicking the right button, becouse it's only getting me mounting it.. hm...

**Comment by Luke100000** [comment]
Shift right, or E from within
