### ISSUE TITLE
1.16.5 recipes broken

### ISSUE THREAD

**Issue by ImplicitSaber** [Luke100000/ImmersiveAircraft#48]
Some recipes on 1.16.5 are broken due to their use of the Copper Ingot (minecraft:copper_ingot) item which was added later. Currently, 3 recipes are affected: Sturdy Pipes (immersive_aircraft:sturdy_pipes), Industrial Gears (immersive_aircraft:industrial_gears), and Enhanced Propeller (immersive_aircraft:enhanced_propeller). The only affected versions are pre-1.17 versions.

**Comment by ImplicitSaber** [comment]
I created a pull request that fixes this issue. However, it does replace all copper in recipes with iron. It may be more balanced to use gold, however iron seems to work. Pull request #49

**Comment by Luke100000** [comment]
Whoops, completely forgot about copper. Thanks! I changed it to gold at some places to keep two materials.
