### ISSUE TITLE
All vehicles unresponsive.

### ISSUE THREAD

**Issue by ArchDev-TroyP** [Luke100000/ImmersiveAircraft#52]
Everything was working fine this morning, then for no apparent reason I am unable to dismount any vehicle all i can do is turn left and right. I have to have another player break the vehicle to free me. happens with all 4 vehicles. Unable to ascend as well. I tried changing the key binds. No joy. i've tried deleting my player data from the server, I also tried removing and re adding the mod. Unsure of what to do next.

**Comment by Luke100000** [comment]
I fixed related issues and since then was unable to reproduce this issue, reopen if I'm wrong
