### ISSUE TITLE
Hoverable airships sometimes lose input (easy workaround for now) (1.16?)

### ISSUE THREAD

**Issue by BrawleyGithub** [Luke100000/ImmersiveAircraft#53]
Sometimes, when piloting a ship that hovers (anything but the biplane), the ship will just stop moving and hover, and will not move forward until the player unpresses and represses W and a few seconds pass. This can be skipped by hitting spacebar, which will ascend the ship slightly and allow movement again immediately. It happens more frequently when moving forward for a while, so it may be an issue with loading chunks causing the inputs to reset?

**Comment by Luke100000** [comment]
Does it happen while hovering, or can you move forward and it suddenly no longer reacts, slows down and then keeps hovering?

**Comment by BrawleyGithub** [comment]
It only happens when holding down w for a bit. It just stops reacting to w unless you're holding space. It's actually happening a lot more than I thought it was, I was in my survival world earlier and it's kinda frequent. The ship just levels off and acts like you're not hitting any buttons.

Sorry for the delay!
