### ISSUE TITLE
(Possibly intentional?) (1.16) gyrocopter breaks instantly when hitting half slabs during startup sequence

### ISSUE THREAD

**Issue by BrawleyGithub** [Luke100000/ImmersiveAircraft#54]
I've run the copter into full blocks while giving it enough motor power and it's been fine, but while I was leaving a sky village my copter hit a half slab on the bridge and broke instantly. This may be intentional but doesn't feel like it unless the real bug is not breaking when hitting full blocks. It could go either way, since the gyrocopter still gains power while "moving" against a solid wall. Will get more info shortly.

**Comment by BrawleyGithub** [comment]
Can confirm reproduceable. I think it depends on how close you are to liftoff, but even at a fairly low percent, I still had it break upon running into a line of slabs, but never break on full blocks.

EDIT: It seems to be ANY incline small enough for the ship to attempt to go up. From a half to a full also breaks it. May be due to the vertical velocity change being counted as a damagable hit?

**Comment by Luke100000** [comment]
Minecraft has no impact by vanilla, I might have abused the collision resolver incorrectly here. Will check that out
