### ISSUE TITLE
Duplication Using Aircraft Inventory

### ISSUE THREAD

**Issue by GGregg112** [Luke100000/ImmersiveAircraft#55]
Found on Forge 1.19.2

Steps to reproduce:
Place items in plane (fuel and inventory) fly to some height then begin flying towards floor at sufficient speed to destroy the plane on collision, before collision open inventory and stay on inventory screen during crash. Inventory screen persists, allowing player to remove the items from the inventory and collect the items dropped by plane from crash.

Expected outcome:
Plane drops inventory and inventory menu closes

Actual outcome:
Inventory screen persists after a crash and after items dropped from crash.

**Comment by Luke100000** [comment]
fixed
