### ISSUE TITLE
Inputs reset (again)

### ISSUE THREAD

**Issue by Luke100000** [Luke100000/ImmersiveAircraft#57]
Using multi keybinds the set keybind does not save.

**Comment by NovelPhacelia** [comment]
Can confirm on fabric 0.14.21-1.19.2 with IA version 0.5.0 and [keyboard layers](https://modrinth.com/mod/bindlayers) 1.0.1

**Comment by lordoftheloidl** [comment]
can confirm on forge version

**Comment by netcore10** [comment]
can confirm with keymap on 1.19.2

**Comment by RuafuMan-Obs** [comment]
can confirm on 1.20.1 forge 47.1.0 ,mod version 0.5.2

**Comment by Luke100000** [comment]
I found that Forge itself modified Keybindings, causing it to fail on load. I retired MultiKeyBinds altogether.

**Comment by OPStellar** [comment]
I'm still having this issue. Is there no way around it?

**Comment by RuafuMan-Obs** [comment]
set "useCustomKeybindSystem" to false,this is what I figured out,hope it works for u

**Comment by NovelPhacelia** [comment]
Still having this issue, havent done further testing but it appears to be between [Dust's KeyMap](https://modrinth.com/mod/dusts-keymap) and IA, this is not a issue if the keybind is set with the vanilla menu but it will reset again if Keymap is opened
