### ISSUE TITLE
Gyrodines stop working

### ISSUE THREAD

**Issue by JustADudeIGuess** [Luke100000/ImmersiveAircraft#58]
For some odd reason, when I was playing Immersive aircrafts on my modpack(made in the curse forge app) and when I loaded in some chunks the gyrodine I was flying stopped working. I tried spawning in another, but that similarly failed. From what I've tested, it only is like this for the gyrodine. I was playing on fabric version 0.14.17 for Minecraft version 1.18.2. No idea if this is a bug or a mod acting weird.

**Comment by Luke100000** [comment]
Most likely related to #53

**Comment by JustADudeIGuess** [comment]
I thought of that, but it only happens for the Gyrodine. Maybe I have a variant of some sort.

**Comment by joemas0192** [comment]
> I thought of that, but it only happens for the Gyrodine. Maybe I have a variant of some sort.

I was apparently having the same "issue" but it turns out that it was just my hunger. So if you seem to have this "bug" you just need to get your hunger bar up. Hope this helps!
Edit: I forgot to mention that your hunger bar still affects you in creative mode.
