### ISSUE TITLE
[Forge 1.19.2, Immersive Aircraft 0.5.0] Keybinds clearing after restart

### ISSUE THREAD

**Issue by Aulberon** [Luke100000/ImmersiveAircraft#60]
If I set the keybinds for the mod, after I reenter de game they all vanish, forcing me to rebind every time.

I'm using the mod [Keymap](https://www.curseforge.com/minecraft/mc-mods/keymap) to deal with my keybinds.

**Comment by f0kx** [comment]
me also having this problem with latest IA version...iam using the controlling mod ... it resets after every reboot of the game...i use R button on the tool belt mod and so it always opens when i want to dismount. i change it but it will reset.

i bind the dismount key to ^ thats a button never used by any other mod

**Comment by Luke100000** [comment]
Let's merge with #57

In the config, there is a flag `useCustomKeybindSystem`. Setting this to false uses another keybind system. Does that help or break something else instead? (R for example has to work as its vanilla, but the other keys may behave funky)

**Comment by Aulberon** [comment]
It sort of work. The problem now is if another action is bound in the same button, the one in immersive aircraft doesn't work.
For example, trying to use LShift as the booster while having it as the run button. It still works for running, but not for boosting.

**Comment by Luke100000** [comment]
Yea thats vanilla behavior. You can basically choose between vanilla restriction of "one action per key" or my custom code which apparently collides with controls mods.
