### ISSUE TITLE
Banners not working on Airships in multiplayer

### ISSUE THREAD

**Issue by SirRosenfeld** [Luke100000/ImmersiveAircraft#64]
When trying to equip the banner on an airship :
- It appears for the player who places the banner
- It doesn't appear for the other players
- If the player who equipped leaves and goes back in the airship, the banner isn't here anymore and is back in the player's inventory

Minecraft 1.20.1
Forge 47.0.19
Immersive Aircrafts 0.5.1

**Comment by Luke100000** [comment]
Most likely related and fixed with #80, if not please respond here
