### ISSUE TITLE
GUI issues / compatibilities - 1.20.1

### ISSUE THREAD

**Issue by zachsai** [Luke100000/ImmersiveAircraft#67]
Incompatible icon placement when TAN is installed: 
![image](https://github.com/Luke100000/ImmersiveAircraft/assets/63996164/d1db0177-9704-4960-99e6-0b81568c0169)

When JEI is installed, the chest placements (guis to put items) are not the greatest, making them make jei wrap around would be best
![image](https://github.com/Luke100000/ImmersiveAircraft/assets/63996164/3e65b912-8911-4055-b56e-4a63cbb9d817)

**Comment by Luke100000** [comment]
No idea how to resolve TAN. For JEI, do you have a reference open source mod who adds a complex gui (something on the right) where JEI wraps?

**Comment by zachsai** [comment]
I am not too sure which mod would do this. I would suggest writing directly to the JEI creator, he/she might be able to help

**Comment by Luke100000** [comment]
JEI support added
