### ISSUE TITLE
Crash while flying Gyrodine *with full hunger

### ISSUE THREAD

**Issue by Nyoom-Monster** [Luke100000/ImmersiveAircraft#68]
So I am playing the Create Re-Flavored modpack on Forge for Minecraft 1.19.2 and I am unable to play my survival world because of a crash that I believe was caused by this mod.

I was flying in a Gyrodine with no modifications over the jungle/desert and that's when my game froze for 10 minutes, then completely crashed with a Minecraft exit code -1. Before this I had been flying the same aircraft just fine, with no issues, through multiple takeoffs and landings. My hunger bar at the time of the crash was full, I checked. Every time I try to reload my world, though, there's the message at the bottom of the screen saying my fuel is too low, despite the hunger bar still being full. I am not able to control my game at all from this point, and anything besides the aircraft, my player model and whatever I'm wearing, and my Inventory HUD GUI are missing. I exist in an empty skybox, frozen in place, unable to interact with the Minecraft window. It takes less than 5 minutes for my game to crash after this, with the same exit code as before.

Below are all the crash reports from my attempts to get the game working again. Last one I added a texture pack and associated data pack that change the textures and recipes of Immersive Aircraft to work better with Create, and the texture did actually display on my Gyrodine, so this cleary isn't a texture loading issue, and doesn't seem to actually be about loading the Gyrodine model, at least, not alone. I'd hoped maybe I could break the loop this way. I did back up my world before the last crash, but not the others, not since 7/2/23.

[crash-2023-07-13_05.43.25-client.txt](https://github.com/Luke100000/ImmersiveAircraft/files/12039483/crash-2023-07-13_05.43.25-client.txt)
[crash-2023-07-13_05.48.07-client.txt](https://github.com/Luke100000/ImmersiveAircraft/files/12039484/crash-2023-07-13_05.48.07-client.txt)
[crash-2023-07-13_06.28.43-client.txt](https://github.com/Luke100000/ImmersiveAircraft/files/12039485/crash-2023-07-13_06.28.43-client.txt)
[crash-2023-07-13_05.30.57-client.txt](https://github.com/Luke100000/ImmersiveAircraft/files/12039486/crash-2023-07-13_05.30.57-client.txt)

**Comment by Luke100000** [comment]
`com.github.teamfusion.rottencreatures.common.entities.Mummy` caused a `net.minecraft.ResourceLocationException: Non [a-z0-9_.-] character in namespace of location: textures/models/armor/environmental:explorer_layer_1.png`

This issue appears related: https://github.com/teamfusion/rottencreatures/issues/23
