### ISSUE TITLE
transport problems on the server

### ISSUE THREAD

**Issue by tutinberg** [Luke100000/ImmersiveAircraft#72]
When the player gets out of the vehicle, the server crashes. I am playing minecraft Forge 1.20.1 - 47.1.37. Version of mod [Forge 1.20.1] Immersive Aircraft - 0.5.1. The error was repeated every time I exit.

**Comment by Luke100000** [comment]
Please append the log

**Comment by tutinberg** [comment]
[2023-07-22-1.log](https://github.com/Luke100000/ImmersiveAircraft/files/12138620/2023-07-22-1.log)

**Comment by Luke100000** [comment]
I can take a look at this but for now I don't support bukkit implementations. They are just too destructive in their injection.

**Comment by Luke100000** [comment]
Merged with #80, most likely technically related
