### ISSUE TITLE
Jump counter counts up infinitely 

### ISSUE THREAD

**Issue by liopyu** [Luke100000/ImmersiveAircraft#77]
If you hold space to ascend with the quadrocopter or any other one of the airships/gyrodyne and dismount it while still holding space bar it infinitely will count the jump statistic up. This messes with some things like a custom jump sound from other mods/packs.
Version 1.19.2-0.5.1

![Screenshot 2023-07-29 103534](https://github.com/Luke100000/ImmersiveAircraft/assets/130418550/089e26c9-73d5-4da1-930d-7c26d1032cce)

**Comment by Luke100000** [comment]
I can't reproduce that, does this happen without any other mods?

**Comment by liopyu** [comment]
Here's a test with just immersive aircraft installed
https://github.com/Luke100000/ImmersiveAircraft/assets/130418550/16bb421f-8c35-406c-b621-937172117331

**Comment by Luke100000** [comment]
Oh I misunderstood the problem, thanks

**Comment by liopyu** [comment]
no problem!
