### ISSUE TITLE
Inventory storage bug in plane

### ISSUE THREAD

**Issue by Sparttt3** [Luke100000/ImmersiveAircraft#80]
Sometimes, when I try to remove an object from my airplane's inventory, I encounter a problem as it doesn't get removed. This issue is quite persistent and annoying.

**Comment by Sparttt3** [comment]
I am completing this; this bug still exists even in the latest version. The items removed from the plane are indeed present in the inventory, but when we open another inventory, they immediately return to the plane.

**Comment by Luke100000** [comment]
Can you name one specific airplane and slot for me to reconstruct please? Do you use shift click or just plain pick and drop? Forge or Fabric?

**Comment by Sparttt3** [comment]
I used the shift left click to remove the items and I play on fabric 1.18.2

for more details 

https://youtu.be/hAGg0oIlgOw

**Comment by MaxenceFrs** [comment]
I confirm the existence of this bug, because I had the same problem several times.

**Comment by talesruan** [comment]
I'm having this bug as well, I hope I can help with more info:

- I'm running a forge server 47.1.46, Minecraft 1.20.1 and Immersive aircraft 0.6.2.
- I had the problem happen with the biplane, cargo airship and quadcopter, so I suspect all vehicles are affected.
- It manifests by shift+click and the usual click and drop too. It blocks transfer of items both ways, cannot put nor remove items from the aircraft inventory, including upgrade and fuel slots. it's like a rollback happens after you close the modal window.
- Destroying and placing the craft again fixes it, but its kind of annoying to do that when it has a full cargo
- Logging out and logging back in does not fix.
- All players are affected by the bug at the same time for a certain vehicle
- A server restart fixes all affected vehicles
- It seems the vehicles do not bug out at the same time, and the longer you interact with the vehicle's inventory, the more probable it is the bug will manifest.

I'm attaching my server's log file. I'm new to minecraft modding so I'm not sure if this is the right log. Let me know if I can help in any way.
[debug.log](https://github.com/Luke100000/ImmersiveAircraft/files/12696821/debug.log)

**Comment by Remithium** [comment]
Can confirm, running forge server 47.2.0, Minecraft 1.20.1 and Immersive Aircraft 0.6.2.
Exactly the same issue as the people above me.

**Comment by codegoose** [comment]
I'm running 0.6.2, MC 1.20.1, Quilt 0.21.2 on a dedicated server and players have been experiencing issues with adding items to the airship inventory. After a player puts items into the ship, those items will be returned to them when they open a container. I've also found the issue to be intermittent and difficult to reliably reproduce and I've not picked up anything in the client or server logs that would seem to help.

For right now, we're giving affected players shulker boxes they can use as a workaround.

**Comment by Mysterious-Wrangler** [comment]
I have another inventory issue, idk if its the same one, but sometimes when i get out of the airplane the inventory glitches out and i have to destroy the plane to fix it.
