### ISSUE TITLE
deactivate recipes

### ISSUE THREAD

**Issue by Nomanoclass** [Luke100000/ImmersiveAircraft#82]
Hello,

I want to make a steampunk server and I need your aircraft only,
therefore, is it possible to deactivate the other recipes?

Thanks in advance.

**Comment by Luke100000** [comment]
Yes, datapacks can do that. Just overwrite the recipe you do not like, e.g. as described here:
https://www.minecraftforum.net/forums/minecraft-java-edition/recent-updates-and-snapshots/2901158-disable-specific-vanilla-crafting-recipes

**Comment by Nomanoclass** [comment]
Oh ok, I'm not up to date. I'll give it a try, thanks.
