### ISSUE TITLE
Server Crash when placing down Cargo Ship [Fabric 1.20.1]

### ISSUE THREAD

**Issue by gamerpotion** [Luke100000/ImmersiveAircraft#93]
Hi, using **immersive_aircraft-0.6.2+1.20.1-fabric.jar**
A server user has reported that every time they place a cargo ship down it crashes the server
installed on DarkRPG modpack/server

Crashlog - https://pastebin.com/nGh80LkS

<img src="https://media.discordapp.net/attachments/1153726710282473574/1154327743597662218/image.png?width=1218&height=676">

**Comment by Luke100000** [comment]
Hi, please try updating (the crash claims the server still uses 0.6.1), it should have been fixed a while ago in 0.6.2. Only server side update required.
