### ISSUE TITLE
quadrocopter

### ISSUE THREAD

**Issue by SanderLiekens1738** [Luke100000/ImmersiveAircraft#98]
Hello world,
I got a problem with my quadrocopter if i enter it I can't fly the engine doesnt start or I cant exit it. I checked my controls if they arent being double used by any chance but that wasn't the case. If anyone knows what might be my error let me know.  Also I got this problem on a minecraft world that has been reuploaded on to a new server.

**Comment by Luke100000** [comment]
Did you add fuel?
